dist: bionic
language: python
sudo: enabled
notifications:
    email: false
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  # install libvmi dependencies
  - sudo apt-get update -qq
  - >
    sudo apt-get install -qq cmake bison flex check libjson-c-dev libglib2.0-dev
    libxenstore3.0 libxen-dev
    libvirt-dev
  # clone, compile and install libvmi
  - git clone https://github.com/libvmi/libvmi /tmp/libvmi
  # avoid changing directory
  - (mkdir /tmp/libvmi/build && cd /tmp/libvmi/build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr && make && sudo make install)

install:
  - pip install .
  - pip install pep8

script:
  - pep8 --show-source -v
  - python -c 'from libvmi import Libvmi'
